### ISSUE TITLE
Regenerate docs for storage/cassandra updates

### ISSUE THREAD

**Issue by rektide** [JanusGraph/docs.janusgraph.org#5]
In https://github.com/JanusGraph/janusgraph/pull/2644 the storage-backend/cassandra.md document was updated and a link to the web page was added to [the Changelog](https://github.com/JanusGraph/janusgraph/pull/2644/files#diff-77f023b99d3d58008351d3e82fc06e6d06ba1bc2da9e41be6329b7fa4f419f05R88). However the web docs do not seem to have been updated & this link does not show the desired content.

Can we regenerate these docs please?

**Comment by porunov** [comment]
The docs has been updated but your link is pointing for 0.5 version instead of 0.6 version which is 'master' right now.
See the updated docs here: https://docs.janusgraph.org/master/storage-backend/cassandra/
